### PR TITLE
[WIP] Builds and runs on KF5 and Qt 5.12

### PR DESCRIPTION
**Pull request by frmdstryr**
I got it to build and run on KDE Neon for #40. There's still some serious issues but it's a start.

ktechlab

1. All override warnings fixed
2. kdebug statments ported to qdebug according to the porting guide
3. KF5 libraries updated in cmakelists
4. KActions replaced with QActions

Very much a WIP still..

### CODE REVIEW

**Comment by zoltanp** [comment]
@frmdstryr  : Great work you managed to get it to build! Meanwhile I've made some fixes and got approximately in the same state in te `wip-kf5-tr1` branch. Do do you feel like help cleaning up the code / fixing broken stuff? Also maybe you have fixed some things which I have missed, so a comparison of the two branches could be useful.

**Comment by frmdstryr** [comment]
I actually started with the `wip-kf5-tr1` branch but it didn't build for me without making some changes.  Yes I'd be interesting in helping.

It would be good to try and setup travis-ci to build ktechlab and work out the required dependencies. 

I pushed some more of the changes I had to make to fix drag and drop and was able to get code editor to open and run the example circuits. Some of the menus are still missing, the scope, and icons are not working in my branch so I'm not sure what is missing there.

ktechlab-updates

**Comment by zoltanp** [comment]
I've merged your commits into the branch wip-kf5-try1-merge1 . Thanks for fixing the text editors and other things. However, I cannot push your commits to KDE as the policy there is that commits should be associated with a person name (not necessarily a real one, AFAIK). Can you provide a name for your contributions?

When pushing to KDE I got this:
```
Counting objects: 432, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (293/293), done.
Writing objects: 100% (432/432), 107.25 KiB | 3.06 MiB/s, done.
Total 432 (delta 411), reused 151 (delta 138)
remote: Resolving deltas: 100% (411/411), completed with 236 local objects.
remote: Audit failure - Commit abf04fd4f90de32dd2c30b8191a7e9e057f1e93e - Non-full name: frmdstryr
remote: Audit failure - Commit abf04fd4f90de32dd2c30b8191a7e9e057f1e93e - Non-full name: frmdstryr
remote: Audit failure - Commit 43925844cfc9060f43d0fda65818e7a1e4f6343b - Non-full name: frmdstryr
remote: Audit failure - Commit 43925844cfc9060f43d0fda65818e7a1e4f6343b - Non-full name: frmdstryr
remote: Audit failure - Commit 7bc4cad1f4edcbac21d11dae0d71de5099bf6aa9 - Non-full name: frmdstryr
remote: Audit failure - Commit 7bc4cad1f4edcbac21d11dae0d71de5099bf6aa9 - Non-full name: frmdstryr
remote: Audit failure - Commit f97d5e2f2e0b90abc121df711249c565196ace8c - Non-full name: frmdstryr
remote: Audit failure - Commit f97d5e2f2e0b90abc121df711249c565196ace8c - Non-full name: frmdstryr
remote: Audit failure - Commit 0273a66b80f21fb1c1fb3c5197d12707f095558f - Non-full name: frmdstryr
remote: Audit failure - Commit 0273a66b80f21fb1c1fb3c5197d12707f095558f - Non-full name: frmdstryr
remote: Audit failure - Commit d6f881f36ae438e647930326c6eab3fce7e402d6 - Non-full name: frmdstryr
remote: Audit failure - Commit d6f881f36ae438e647930326c6eab3fce7e402d6 - Non-full name: frmdstryr
remote: FATAL: VREF/kde-update-checks: helper program exit status 256
remote: Push declined - commits failed audit
remote: error: hook declined to update refs/heads/wip-kf5-try1
To git.kde.org:ktechlab.git
 ! [remote rejected]   wip-kf5-try1 -> wip-kf5-try1 (hook declined)
error: failed to push some refs to 'git@git.kde.org:ktechlab.git'

```

**Comment by zoltanp** [comment]
Ping... about the contributor name to be used for contributions. I'm fine with any name.

Without having a contributor name I cannot push the code to KDE, thus I cannot integrate your commits into the main development branch. And at some point I need to fix the same issues that you have already fixed, so I either integrate your fixes, or have to reimplement them. I prefer to integrate, but for that I do not want to invent some name, and I'm fine with any name, invented or not.

**Comment by frmdstryr** [comment]
Can the name be set by you or does this require me to change my git name?

**Comment by zoltanp** [comment]
I can edit the `author` field in the commits and push the rewritten branch. As far as I know the author field in the commits is independent of the KDE accounts. For example in KTechLab's git history there are commits from people who do not have a KDE account.

**Comment by zoltanp** [comment]
Merged into `wip-kf5-try1`. Closing this pull request. Please review the git history and if you have any remarks, please let me know.

**Pull request closed without merging**
