### PR TITLE
Create ccpp.yml

### PR DESCRIPTION
**Pull request by ryry071893**

### CODE REVIEW

**Comment by zoltanp** [comment]
Hi,

what is this `cccp.yml` and what it tries to achieve? As I see it it will not work in any case because it has to do something with autotools (./configure), while KTechLab uses CMake.

Also please note that this Github repository is just a mirror; the official git repository of KTechLab is at KDE: https://cgit.kde.org/ktechlab.git/

**Review by Reynolds251 — APPROVED** [review]

**Comment by Reynolds251** [comment]
> Hi,
> 
> what is this `cccp.yml` and what it tries to achieve? As I see it it will not work in any case because it has to do something with autotools (./configure), while KTechLab uses CMake.
> 
> Also please note that this Github repository is just a mirror; the official git repository of KTechLab is at KDE: https://cgit.kde.org/ktechlab.git/

**Comment by Reynolds251** [comment]
> _No description provided._

**Review by Reynolds251 — APPROVED** [review]

**Comment by Reynolds251** [comment]
> _No description provided._

**Comment by Reynolds251** [comment]
gh pr checkout 59

**Comment by zoltanp** [comment]
It's not clear to me what happened recently in the comment section of this issue.
As here has been no recent relevant activity, closing this issue.

**Pull request closed without merging**
